export const INIT_STAGE = "INIT_STAGE";
export const GAME_LOADING_STAGE = "GAME_LOADING_STAGE";
export const GAME_STAGE = "GAME_STAGE";
export const GAME_WAITING_OPPONENT_TURN_STAGE = "GAME_WAITING_OPPONENT_TURN_STAGE";
export const GAME_TURN_RESULT_STAGE = "GAME_TURN_RESULT_STAGE";

export const SET_INIT_STAGE = "SET_INIT_STAGE";
export const SET_GAME_LOADING_STAGE = "SET_GAME_LOADING_STAGE";
export const SET_GAME_STAGE = "SET_GAME_STAGE";
export const SET_GAME_WAITING_OPPONENT_TURN_STAGE = "SET_GAME_WAITING_OPPONENT_TURN_STAGE";
export const SET_GAME_TURN_RESULT_STAGE = "SET_GAME_TURN_RESULT_STAGE";
export const SET_GAME_RESULTS_STAGE = "SET_GAME_RESULTS_STAGE";

export const SET_MY_ICON =  "SET_MY_ICON";
export const SET_OPPONENT_ICON =  "SET_OPPONENT_ICON";
export const UNSET_WINNER =  "UNSET_WINNER";

export const WINNER_ME=  "WINNER_ME";
export const WINNER_NONE =  "WINNER_NONE";
export const WINNER_OPPONENT =  "WINNER_OPPONENT";

export const SET_WINNER_ME=  "SET_WINNER_ME";
export const SET_WINNER_NONE =  "SET_WINNER_NONE";
export const SET_WINNER_OPPONENT =  "SET_WINNER_OPPONENT";

export const SET_READY_ME =  "SET_READY_ME";
export const SET_READY_OPPONENT =  "SET_READY_OPPONENT";
export const UNSET_READY_ME =  "UNSET_READY_ME";
export const UNSET_READY_OPPONENT =  "UNSET_READY_OPPONENT";

